spring.application.name=paofresquim-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/fresquim
spring.datasource.username=userfresquim
spring.datasource.password=joaquim123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true